runtime: python39

entrypoint: gunicorn -b :$PORT "api.new-gpt.main:app"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  OPENAI_API_KEY: "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"